# Generated by Django 4.1.5 on 2023-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_record_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
