# Generated by Django 4.1.5 on 2023-02-02 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_record_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
