# Generated by Django 4.1.5 on 2023-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_record_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home', models.IntegerField(default=0)),
                ('shop', models.IntegerField(default=0)),
            ],
        ),
    ]
