# Generated by Django 4.1.5 on 2023-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_record_options_record_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='order_id',
            field=models.CharField(default='1111111', max_length=20),
        ),
    ]
