# Generated by Django 4.1.5 on 2023-03-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_record_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('wire', 'Wire Cable'), ('board', 'Distribution Board'), ('china_light', 'China Light')], default='wire', max_length=100),
        ),
    ]
