# Generated by Django 4.1.5 on 2023-04-04 05:51

from django.db import migrations, models
import django.db.models.deletion

def migrate_data(apps, schema_editor):
    Stock = apps.get_model('api', 'Stock')
    Product = apps.get_model('api', 'Product')
    for item in Stock.objects.all():
        try:
            product = Product.objects.get(name=item.name)
            if product:
                item.product = product
                item.save()
        except Product.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.RunPython(migrate_data),
    ]
