# Generated by Django 4.1.5 on 2023-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vendor_payment_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('income', 'Payment In(income)'), ('expense', 'Payment Out(expense)'), ('stock_in', 'Stock In(debit)')], default='income', max_length=50),
        ),
    ]
