# Generated by Django 4.1.5 on 2023-06-23 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_alter_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('product__name',)},
        ),
        migrations.RemoveField(
            model_name='record',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='record',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='HSN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_replacement',
            field=models.BooleanField(default=False, verbose_name='Replacement/Return'),
        ),
        migrations.AlterField(
            model_name='record',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return')], default='sale', max_length=80)),
                ('total_amount', models.FloatField(default=0.0)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.CharField(default='1111111', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sale_date', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return')], default='purchase', max_length=80)),
                ('invoice_amount', models.FloatField(default=0.0)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_recieved_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_on'),
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.type'),
        ),
        migrations.AddField(
            model_name='record',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder'),
        ),
        migrations.AddField(
            model_name='record',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.saleorder'),
        ),
    ]
