# Generated by Django 4.1.5 on 2023-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_brand_category_itemmodel_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('product',)},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='home',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shop',
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank transfer', 'Bank Transfer(NEFT/RTGS)')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.CharField(choices=[('shop', 'Shop'), ('home', 'Home'), ('po_godown', 'Post Office Godown'), ('colony', 'Teacher Colony Godown'), ('hameerpur', 'Hameerpur Road')], default='home', max_length=100),
        ),
    ]
