# Generated by Django 4.1.5 on 2023-07-11 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_alter_record_options_rename_user_id_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='order_type',
        ),
        migrations.CreateModel(
            name='SaleReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0.0)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.CharField(default='11111', max_length=7)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-return_date', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.FloatField(default=0.0)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_return_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendor')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_on'),
            },
        ),
        migrations.AddField(
            model_name='record',
            name='purchasereturn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.purchasereturnorder'),
        ),
        migrations.AddField(
            model_name='record',
            name='salereturn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salereturnorder'),
        ),
    ]
