# Generated by Django 4.1.5 on 2023-08-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_productlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='order_id',
            field=models.CharField(default='1111111', max_length=15),
        ),
    ]
