# Generated by Django 4.1.5 on 2023-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_saleorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
