# Generated by Django 4.1.5 on 2023-08-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_customer_opening_balance_vendor_opening_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_wh', models.CharField(blank=True, choices=[('shop', 'Shop'), ('home', 'Home'), ('po_godown', 'Post Office Godown'), ('colony', 'Teacher Colony Godown'), ('hameerpur', 'Hameerpur Road')], max_length=100, null=True)),
                ('to_wh', models.CharField(blank=True, choices=[('shop', 'Shop'), ('home', 'Home'), ('po_godown', 'Post Office Godown'), ('colony', 'Teacher Colony Godown'), ('hameerpur', 'Hameerpur Road')], max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
