# Generated by Django 4.1.5 on 2023-08-27 03:21

from django.db import migrations, models

def move_data(apps, schema_editor):
    # We can't import the Payment model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Payment = apps.get_model("api", "Payment")
    for pay in Payment.objects.all():
        pay.payment_date = pay.created_on
        pay.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(move_data),
    ]
